# generated by datamodel-codegen:
#   filename:  change-manifest.schema.json
#   timestamp: 2026-06-14T07:39:42+00:00

from __future__ import annotations

from enum import Enum

from pydantic import BaseModel, ConfigDict, Field


class Operator(Enum):
    add = 'add'
    update = 'update'
    remove = 'remove'
    narrow = 'narrow'
    gate = 'gate'


class Layer(Enum):
    execution = 'execution'
    tooling = 'tooling'
    context = 'context'
    lifecycle = 'lifecycle'
    observability = 'observability'
    verification = 'verification'
    governance = 'governance'


class RepairSpec(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    editable_resources: list[str]
    forbidden_artifacts: list[str] | None = None
    required_behaviors: list[str] | None = None
    validation_criteria: list[str]


class Prediction(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    expected_fixes: list[str]
    at_risk_regressions: list[str]
    rationale: str | None = None


class Verdict(Enum):
    pending = 'pending'
    effective = 'effective'
    partial = 'partial'
    ineffective = 'ineffective'
    harmful = 'harmful'


class Result(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    fixes_verified: list[str] | None = None
    regressions_observed: list[str] | None = None
    unattributed_regressions: list[str] | None = None


class Change(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    change_id: str
    operator: Operator
    component_id: str
    layer: Layer
    summary: str | None = None
    failure_evidence: str
    root_cause: str
    repair_spec: RepairSpec
    prediction: Prediction
    verdict: Verdict | None = None
    result: Result | None = None
    commit: str | None = None


class HDPEvolutionChangeManifest(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    hdp: str = Field(..., pattern='^0\\.1$')
    iteration: int = Field(..., ge=0)
    author: str | None = None
    timestamp: str | None = None
    changes: list[Change]
