# generated by datamodel-codegen:
#   filename:  hdp.schema.json
#   timestamp: 2026-06-14T07:39:25+00:00

from __future__ import annotations

from enum import Enum
from typing import Any

from pydantic import BaseModel, ConfigDict, Field


class Meta(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: str = Field(..., pattern='^[a-z0-9][a-z0-9-]*$')
    version: str = Field(..., pattern='^\\d+\\.\\d+\\.\\d+$')
    name: str | None = None
    description: str | None = None
    base_model: str | None = None
    authors: list[str] | None = None
    targets: list[str] | None = None
    tags: list[str] | None = None


class Evolution(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    editable: list[str] | None = None
    read_only: list[str] | None = None
    protected: list[str] | None = None


class Audit(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    log_all_tool_calls: bool | None = None
    retention_days: int | None = Field(None, ge=0)


class Evaluation(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    benchmark: str
    primary_metric: str
    baseline: float | None = None
    token_budget_per_trial: int | None = None


class Operator(Enum):
    add = 'add'
    update = 'update'
    remove = 'remove'
    narrow = 'narrow'
    gate = 'gate'


class Evolution1(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    manifest_dir: str | None = None
    operators: list[Operator] | None = None


class BlastRadius(Enum):
    read_only = 'read_only'
    local = 'local'
    session = 'session'
    system = 'system'
    external = 'external'


class Kind(Enum):
    mcp = 'mcp'
    package = 'package'
    path = 'path'
    adapter = 'adapter'
    builtin = 'builtin'


class Ref(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    kind: Kind
    server: str | None = None
    package: str | None = None
    path: str | None = None
    binding: str | None = None
    import_: str | None = Field(None, alias='import')


class Type(Enum):
    sandbox = 'sandbox'
    tool = 'tool'
    system_rules = 'system_rules'
    skill = 'skill'
    memory = 'memory'
    loop = 'loop'
    middleware = 'middleware'
    sub_agent = 'sub_agent'
    tracer = 'tracer'
    verifier = 'verifier'
    policy = 'policy'


class Hook(Enum):
    contract_injection = 'contract_injection'
    skill_retrieval = 'skill_retrieval'
    action_validation = 'action_validation'
    trajectory_regulation = 'trajectory_regulation'
    before_model = 'before_model'
    after_model = 'after_model'
    before_tool = 'before_tool'
    after_tool = 'after_tool'


class Scope(Enum):
    session = 'session'
    persistent = 'persistent'
    shared = 'shared'


class Trigger(Enum):
    before_exit = 'before_exit'
    on_demand = 'on_demand'
    periodic = 'periodic'
    external = 'external'


class OnFailure(Enum):
    block_exit = 'block_exit'
    warn = 'warn'
    retry = 'retry'


class Enforcement(Enum):
    hard_block = 'hard_block'
    soft_warn = 'soft_warn'
    log_only = 'log_only'


class Isolation(Enum):
    container = 'container'
    microvm = 'microvm'
    os_permission = 'os_permission'
    wasm = 'wasm'
    none = 'none'


class Component(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: str = Field(..., pattern='^[a-z0-9][a-z0-9-]*$')
    type: Type
    name: str | None = None
    description: str | None = None
    file: str | None = None
    ref: Ref | None = None
    schema_: dict[str, Any] | None = Field(None, alias='schema')
    blast_radius: BlastRadius | None = None
    implementation: Ref | None = None
    hook: Hook | None = None
    impl: Ref | None = None
    scope: Scope | None = None
    trigger: Trigger | None = None
    on_failure: OnFailure | None = None
    contract: dict[str, Any] | None = None
    rule: str | None = None
    enforcement: Enforcement | None = None
    applies_to: list[str] | None = None
    isolation: Isolation | None = None
    backend: Ref | None = None
    cpus: float | None = None
    memory_mb: int | None = None
    timeout_sec: int | None = None
    max_iterations: int | None = Field(None, ge=1)
    tool_call_mode: str | None = None
    stop_tools: list[str] | None = None
    definition: Ref | None = None
    max_depth: int | None = Field(None, ge=0)
    params: dict[str, Any] | None = None


class Layers(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    execution: list[Component] | None = None
    tooling: list[Component] | None = None
    context: list[Component] | None = None
    lifecycle: list[Component] | None = None
    observability: list[Component] | None = None
    verification: list[Component] | None = None
    governance: list[Component] | None = None


class Governance(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    blast_radius: BlastRadius | None = None
    evolution: Evolution | None = None
    audit: Audit | None = None


class HarnessDefinitionProtocolManifestHdpYaml(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    hdp: str = Field(..., pattern='^0\\.1$')
    meta: Meta
    layers: Layers
    governance: Governance | None = None
    evaluation: Evaluation | None = None
    evolution: Evolution1 | None = None
    extensions: dict[str, Any] | None = None
